name: readme_self_hosted

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'

jobs:
  python:
    runs-on: self-hosted
    steps:
    - name: Create temp dir on network drive
      run: |
        TEMP_DIR="/mnt/cluster-workspace/sfonxu/CI/tmp_${{ github.run_id }}_${{ github.run_attempt }}"
        mkdir -p "$TEMP_DIR"
        echo "TEMP_DIR=$TEMP_DIR" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify
      run: |
        echo "Workspace: $GITHUB_WORKSPACE"
        echo "Temp dir: $TEMP_DIR"
        ls -la "$TEMP_DIR"
    - name: Create Venv
      run: |
        python -m venv "$TEMP_DIR/venv"

    - name: Install numba-mpi from checkout
      run: |
        set -v
        . $TEMP_DIR/venv/bin/activate
        pip install .
        python -c "import numba_mpi"
    
    - name: Cleanup
      if: always()
      run: rm -rf "$TEMP_DIR"
