name: readme_self_hosted

defaults:
  run:
    shell: bash

env:
  PYENV_ROOT: /mnt/cluster-workspace/sfonxu/CI/.pyenv

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'

jobs:
  python:
    runs-on: self-hosted
    steps:
    - name: Create temp dir on network drive
      run: |
        TEMP_DIR="/mnt/cluster-workspace/sfonxu/CI/tmp_${{ github.run_id }}_${{ github.run_attempt }}"
        mkdir -p "$TEMP_DIR"
        echo "TEMP_DIR=$TEMP_DIR" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify
      run: |
        echo "Workspace: $GITHUB_WORKSPACE"
        echo "Temp dir: $TEMP_DIR"
        ls -la "$TEMP_DIR"
        
    - name: Create Venv and Install numba_mpi
      run: |
        export PATH=$PYENV_ROOT/bin:$PATH
        pyenv local 3.13.13
        eval "$(pyenv init - bash)"
        set -ex
        python3 -m venv "$TEMP_DIR/venv" --system-site-packages
        . $TEMP_DIR/venv/bin/activate
        # pip install .
        python -c "print('Hello world!')"
        python --version

    - name: Run calculations on compute nodes
      run: |
        set -ex
        export SCRIPT='export PATH=$PYENV_ROOT/bin:$PATH; pyenv local 3.13.13; eval "$(pyenv init - bash)"; python3 --version'
        srun --chdir=$TEMP_DIR -N1 -w ground-control /bin/bash -c "$SCRIPT"      
        srun --chdir=$TEMP_DIR -N1 -w major-tom /bin/bash -c "$SCRIPT"

    - name: Cleanup
      if: always()
      run: rm -rf "$TEMP_DIR"
